create table
  feedbacks (
    id bigint generated by default as identity primary key,
    full_name text not null,
    phone_number text not null,
    email text,
    note text not null,
    created_at timestamp with time zone
  );

alter table feedbacks enable row level security;

create policy "Auth users can see feedbacks" on feedbacks for
select
  to authenticated using (true);

create policy "Public can create feedback" on feedbacks for insert to anon
with
  check (true);